name: tribely_flutter

packages:
  - apps/mobile
  - apps/mobile/packages/**

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  analyze:
    description: Run flutter analyze on all Flutter packages
    run: melos exec -- flutter analyze
    packageFilters:
      flutter: true

  test:
    description: Run flutter test on all Flutter packages
    run: melos exec -- flutter test
    packageFilters:
      flutter: true

  format:
    description: Run dart format on all Flutter packages
    run: melos exec -- dart format .
    packageFilters:
      flutter: true

  build_runner:
    description: Run build_runner once on all relevant packages
    run: melos exec -- dart run build_runner build --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner

  build_runner:watch:
    description: Run build_runner in watch mode
    run: melos exec -- dart run build_runner watch --delete-conflicting-outputs
    packageFilters:
      dependsOn: build_runner
