// TODO(TRI-32 follow-up): fetch /picklists endpoint instead of hardcoding.

const Map<String, String> kLanguageLabels = {
  'en': 'English',
  'zh': 'Mandarin Chinese',
  'yue': 'Cantonese',
  'ms': 'Malay',
  'ta': 'Tamil',
  'hi': 'Hindi',
  'ja': 'Japanese',
  'ko': 'Korean',
  'fr': 'French',
  'de': 'German',
  'es': 'Spanish',
  'pt': 'Portuguese',
  'it': 'Italian',
  'nl': 'Dutch',
  'ru': 'Russian',
  'ar': 'Arabic',
  'th': 'Thai',
  'vi': 'Vietnamese',
  'id': 'Indonesian',
  'tl': 'Filipino/Tagalog',
};

const Map<String, String> kInterestLabels = {
  'drinks': 'Drinks',
  'food': 'Food',
  'coffee': 'Coffee',
  'hike': 'Hiking',
  'cycling': 'Cycling',
  'running': 'Running',
  'yoga': 'Yoga',
  'gym': 'Gym',
  'swimming': 'Swimming',
  'team_sports': 'Team Sports',
  'museum': 'Museum',
  'art': 'Art',
  'music': 'Music',
  'theatre': 'Theatre',
  'film': 'Film',
  'board_games': 'Board Games',
  'photography': 'Photography',
  'reading': 'Reading',
  'cooking': 'Cooking',
  'language_exchange': 'Language Exchange',
  'travel': 'Travel',
  'nightlife': 'Nightlife',
  'beach': 'Beach',
  'nature': 'Nature',
  'tech': 'Tech',
  'startups': 'Startups',
  'finance': 'Finance',
  'volunteering': 'Volunteering',
  'wellness': 'Wellness',
  'other': 'Other',
};

const Map<String, String> kTravelerTypeLabels = {
  'local': 'Local',
  'traveling': 'Traveling',
  'expat': 'Expat',
};
